/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAOConexao.DAOBase;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author adavilson
 */
public class TelaPrincipalMDI extends javax.swing.JFrame {
    DAOBase controleDaoBase= new DAOBase();
    /**
     * Creates new form TelaPrincipalMDI
     */
    public TelaPrincipalMDI() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        TelaCadastroCliente = new javax.swing.JMenu();
        jMenuCadastroCliente = new javax.swing.JMenuItem();
        jMenuSecretaria = new javax.swing.JMenu();
        jMenuCadastroSecretaria = new javax.swing.JMenuItem();
        jMenuCadastroEscritorio = new javax.swing.JMenu();
        menuCadastroEscritorio = new javax.swing.JMenuItem();
        jMenuCadastroAdvogado = new javax.swing.JMenu();
        menuAdvogado = new javax.swing.JMenuItem();
        jMenuCadastroComarca = new javax.swing.JMenu();
        MenuComarca = new javax.swing.JMenuItem();
        jMenuMovimentacao = new javax.swing.JMenu();
        jMenuHonorarios = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuProcesso = new javax.swing.JMenu();
        cadastroProcesso = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenu();
        ClienteRelatorio = new javax.swing.JMenuItem();

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem13.setText("jMenuItem13");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(java.awt.Color.blue);
        jDesktopPane1.setForeground(new java.awt.Color(204, 0, 0));
        jDesktopPane1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jDesktopPane1.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagem do escritorio.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setAutoscrolls(true);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel2.setDoubleBuffered(true);
        jLabel2.setFocusCycleRoot(true);
        jLabel2.setFocusTraversalPolicyProvider(true);
        jLabel2.setInheritsPopupMenu(false);
        jLabel2.setOpaque(true);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        jDesktopPane1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setToolTipText("Menu ");
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setEnabled(false);

        jMenuCadastro.setText("Cadastro");

        TelaCadastroCliente.setText("Clientes");

        jMenuCadastroCliente.setText("Cadastrar Clientes");
        jMenuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroClienteActionPerformed(evt);
            }
        });
        TelaCadastroCliente.add(jMenuCadastroCliente);

        jMenuCadastro.add(TelaCadastroCliente);

        jMenuSecretaria.setText("Secretaria");

        jMenuCadastroSecretaria.setText("Cadastro Secretaria");
        jMenuCadastroSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroSecretariaActionPerformed(evt);
            }
        });
        jMenuSecretaria.add(jMenuCadastroSecretaria);

        jMenuCadastro.add(jMenuSecretaria);

        jMenuCadastroEscritorio.setText("Escritorio");

        menuCadastroEscritorio.setText("Cadastro Escritorio");
        menuCadastroEscritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroEscritorioActionPerformed(evt);
            }
        });
        jMenuCadastroEscritorio.add(menuCadastroEscritorio);

        jMenuCadastro.add(jMenuCadastroEscritorio);

        jMenuCadastroAdvogado.setText("Advogado");

        menuAdvogado.setText("Cadastro Advogado");
        menuAdvogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdvogadoActionPerformed(evt);
            }
        });
        jMenuCadastroAdvogado.add(menuAdvogado);

        jMenuCadastro.add(jMenuCadastroAdvogado);

        jMenuCadastroComarca.setText("Comarca");

        MenuComarca.setText("Cadastro Comarca");
        MenuComarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuComarcaActionPerformed(evt);
            }
        });
        jMenuCadastroComarca.add(MenuComarca);

        jMenuCadastro.add(jMenuCadastroComarca);

        jMenuBar1.add(jMenuCadastro);

        jMenuMovimentacao.setText("Movimentação");

        jMenuHonorarios.setText("Honorários");

        jMenuItem34.setText("Cadastrar Honorários");
        jMenuHonorarios.add(jMenuItem34);

        jMenuMovimentacao.add(jMenuHonorarios);

        jMenuProcesso.setText("Processo");

        cadastroProcesso.setText("Cadastrar Processo");
        cadastroProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroProcessoActionPerformed(evt);
            }
        });
        jMenuProcesso.add(cadastroProcesso);

        jMenuMovimentacao.add(jMenuProcesso);

        jMenuBar1.add(jMenuMovimentacao);

        jMenuRelatorio.setText("Relatórios");

        jMenuClientes.setText("Clientes");

        ClienteRelatorio.setText("Relatorio de Cliente");
        ClienteRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteRelatorioActionPerformed(evt);
            }
        });
        jMenuClientes.add(ClienteRelatorio);

        jMenuRelatorio.add(jMenuClientes);

        jMenuBar1.add(jMenuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroSecretariaActionPerformed

        TelaCadastroSecretaria telaCadastroSecretaria = new TelaCadastroSecretaria();
        jDesktopPane1.add(telaCadastroSecretaria);
        telaCadastroSecretaria.setVisible(true);

    }//GEN-LAST:event_jMenuCadastroSecretariaActionPerformed

    private void jMenuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroClienteActionPerformed
        TelaCadastroCliente telaCadastroCliente = new TelaCadastroCliente();
        jDesktopPane1.add(telaCadastroCliente);
        telaCadastroCliente.setVisible(true);


    }//GEN-LAST:event_jMenuCadastroClienteActionPerformed

    private void menuCadastroEscritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroEscritorioActionPerformed

        TelaCadastroEscritorio telaCadastroEscritorio = new TelaCadastroEscritorio();
        jDesktopPane1.add(telaCadastroEscritorio);
        telaCadastroEscritorio.setVisible(true);

    }//GEN-LAST:event_menuCadastroEscritorioActionPerformed

    private void menuAdvogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdvogadoActionPerformed
        TelaCadastroAdvogado telaCadastroAdvogado;
        try {
            telaCadastroAdvogado = new TelaCadastroAdvogado();
             jDesktopPane1.add(telaCadastroAdvogado);
        telaCadastroAdvogado.setVisible(true);  
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipalMDI.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }//GEN-LAST:event_menuAdvogadoActionPerformed

    private void MenuComarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuComarcaActionPerformed

        TelaCadastroComarca telaCadastroComarca = new TelaCadastroComarca();
        jDesktopPane1.add(telaCadastroComarca);
        telaCadastroComarca.setVisible(true);


    }//GEN-LAST:event_MenuComarcaActionPerformed

    private void cadastroProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroProcessoActionPerformed
        TelaCadastroProcesso telaCadastroProcesso = new TelaCadastroProcesso();
        jDesktopPane1.add(telaCadastroProcesso);
        telaCadastroProcesso.setVisible(true);


    }//GEN-LAST:event_cadastroProcessoActionPerformed

    private void ClienteRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteRelatorioActionPerformed

    }//GEN-LAST:event_ClienteRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TelaPrincipalMDI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClienteRelatorio;
    private javax.swing.JMenuItem MenuComarca;
    private javax.swing.JMenu TelaCadastroCliente;
    private javax.swing.JMenuItem cadastroProcesso;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuCadastroAdvogado;
    private javax.swing.JMenuItem jMenuCadastroCliente;
    private javax.swing.JMenu jMenuCadastroComarca;
    private javax.swing.JMenu jMenuCadastroEscritorio;
    private javax.swing.JMenuItem jMenuCadastroSecretaria;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuHonorarios;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenu jMenuMovimentacao;
    private javax.swing.JMenu jMenuProcesso;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuSecretaria;
    private javax.swing.JMenuItem menuAdvogado;
    private javax.swing.JMenuItem menuCadastroEscritorio;
    // End of variables declaration//GEN-END:variables
}
